name: prescribed
description: Digital Health App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.1
  google_maps_flutter: ^1.1.1
  cupertino_icons: ^1.0.0
  curved_navigation_bar:
  http: ^0.12.2
  animated_splash_screen: ^1.0.1+2
  sqflite: ^1.3.0
  path_provider: ^1.6.24
  path: ^1.7.0
  flutter_gradient_colors: ^1.0.0
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  speech_recognition: ^0.3.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0

flutter:
  uses-material-design: true
  assets:  
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp/MyFlutterApp.ttf   
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
    - family: DidactGothic
      fonts:
        - asset: assets/fonts/DidactGothic/DidactGothic-Regular.ttf
